package personality;

import java.lang.Object

import java.util.Random
import java.util.List
import java.util.Optional
import java.util.logging.Logger
import java.util.Arrays
import java.util.ArrayList
import java.util.Collections
import java.util.stream.Collectors
import java.util.LinkedList

import org.javatuples.Pair


import org.salve.personality.model.DialogueTree
import org.salve.personality.model.Believes
import org.salve.personality.*

import org.salve.drools.model.values.PerlocutionaryValueSet
import org.salve.drools.model.template.db.MatchedQueryDatabase
import org.salve.drools.model.template.db.QueryDatabase
import org.salve.drools.model.*
import org.salve.drools.SymbolCapture

import dialogue.FinishedProcess
import dialogue.DefaultReply
import dialogue.PreProcessed
import dialogue.Reply

global Logger log
global org.salve.drools.controller.DroolInterface controller
global Random random

