package dialogue

import org.salve.drools.model.template.db.CapturedMatchDB
import org.salve.drools.model.template.db.QueryDatabase
import org.salve.drools.model.db.SymbolDatabase
import org.salve.drools.model.db.PatternDatabase
import org.salve.drools.model.db.PatternCollection
import org.salve.drools.model.values.PersonalValues
import org.salve.drools.model.Utterance
import org.salve.drools.model.Informative
import org.salve.drools.model.Symbol
import org.salve.drools.model.Scene
import org.salve.drools.model.Actor
import org.salve.drools.model.Goal
import org.salve.drools.model.PatternSymbol
import org.salve.drools.model.Utterance
import org.salve.drools.ParsedUtterance
import org.salve.drools.UnparsedUserUtterance
import org.salve.drools.ParsedUtterance
import org.salve.drools.SymbolCapture

import java.lang.Float
import java.lang.String
import java.util.EnumMap
import java.util.List
import java.util.Arrays
import java.util.ArrayList
import java.util.HashSet
import java.util.Collections
import java.util.Optional
import java.util.stream.Collectors
import java.util.Set
import java.util.Random
import java.util.logging.Logger

import org.javatuples.Pair

global Logger log;
global Random random;

import com.google.common.collect.Sets

